PCA算法

In [1]:
import  numpy as np 
from numpy.linalg import eig

b,s =4,2
x=np.random.rand(b,s)
print(x)

[[0.521018   0.75805698]
 [0.17513316 0.39912923]
 [0.78688245 0.20439685]
 [0.27139373 0.0682793 ]]


In [2]:
u=x.mean(axis=0)
print(u)

[0.43860683 0.35746559]


In [3]:
x-u

array([[ 0.08241116,  0.40059138],
       [-0.26347368,  0.04166364],
       [ 0.34827562, -0.15306874],
       [-0.1672131 , -0.28918629]])

In [4]:
#cov_mat =(x-u).T @ (x-u)
cov_mat = x.T@x
print(cov_mat)

[[0.99496992 0.64422896]
 [0.64422896 0.78039466]]


In [5]:
lam,v =eig(cov_mat)
lam

array([1.54078381, 0.23458078])

In [6]:
lam_index = np.argsort(lam)[::-1]
print(lam_index)
print(lam[lam_index])

[0 1]
[1.54078381 0.23458078]


In [7]:
lam_sorted =lam[lam_index]
v_sorted = v[:,lam_index]

a = v_sorted
x_components =(x-u)@ (-v_sorted)

x_components.shape

(4, 2)

In [8]:
r = lam_sorted / lam.sum()
print(r)

[0.86786896 0.13213104]


In [9]:
np.sum(r[:3])

1.0

In [10]:
x_components[:,:3]

array([[-0.32182956, -0.25237034],
       [ 0.17409255, -0.20210399],
       [-0.16677981,  0.34192169],
       [ 0.31451682,  0.11255264]])

In [23]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
pca.fit(x)

PCA(n_components=2)

In [20]:
x_components_pca = pca.fit_transform(x)

x_components_pca[:,:3]

array([[ 0.40561888, -0.05232954],
       [-0.04627546, -0.26270291],
       [-0.03149983,  0.37912228],
       [-0.3278436 , -0.06408983]])

In [24]:
pca.explained_variance_.sum()

0.16491138964193355

PCA小结
实现了-PCA算法
    -协方差矩阵
    -排序
    -变换
    -贡献率
    -变换矩阵